#!/bin/bash

TOOL_PATH="/home/vcap/app/.bp-config/Module_Active_Data"
RAW_DATA_PATH="/home/vcap/app/.bp-config//Module_Active_Data/active_cert_pull"
MY_BACKUP_PATH="/var/vcap/data/LHI/Module_Active_Data"

#cd $TOOL_PATH/results
#rm *.log
#cd ..

today=`date '+%m_%d_%Y'`;
LOG_FILENAME="$TOOL_PATH/results/$today.ACTIVE.log"

echo "=================================================================================="

#remove todays log_file only just in case I am debugging
rm $LOG_FILENAME   

#clean out the Active Table for a fresh start. Should only use this for debugging purposes.
#$TOOL_PATH/delete_data_active_table   

i=1

for f in `ls $RAW_DATA_PATH/ | sort -n`
do
	
	echo "$i: Processing $RAW_DATA_PATH/$f file..."

  	$TOOL_PATH/active_to_sql $RAW_DATA_PATH/$f  >> $LOG_FILENAME
  	echo "$i: ################"   >> $LOG_FILENAME

  	# If I have any error messages in the log, I'll pop up a window in ubuntu to notify me. This will pause execution when true.
	#grep -q -i "error" $LOG_FILENAME && zenity --error --text="Active Table Error Found\!" --title="Warning\!"
	

	((i+=1))
done

#echo "Marking all dup rows in the CMVP_Active_Table. Plus create a clean_lab_name by using just the first word of the lab name since there are many spellings." 
$TOOL_PATH/Mark_Active_Table_Dups >> $LOG_FILENAME

# Backup all my log files to the Network Share Drive
cp $TOOL_PATH/results/* $MY_BACKUP_PATH/results/.

#grep -q -i "error"  $TOOL_PATH/results/*.log && zenity --error --text="Active Table Error Found\!" --title="Warning\!"
	

